controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

entities:
    resource:
        path: ../src/Entity
        namespace: App\Entity
    type: attribute

repositories:
    resource:
        path: ../src/Repository
        namespace: App\Repository
    type: attribute

normalizers:
    resource:
        path: ../src/Normalizer
        namespace: App\Normalizer
    type: attribute

api_login_check:
    path: /auth/login
    methods: [POST]